name: tutero-analysis
run-name: ${{ github.actor }} is learning GitHub Actions
on: [pull_request]
jobs:
  tutero-analysis:
    name: Tutero Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.6'
        channel: 'stable'
    - run: flutter --version
    - run: flutter pub get
